version: "3"

services:
    projetdemo_mysql:
        image: mysql:8
        volumes:
            - .db_data:/var/lib/mysql
            - ./docker/local/mysql:/etc/mysql/conf.d
        restart: always
        ports:
            - "3301:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: projetdemo

volumes:
  .db_data: {}
